apiVersion: v2
name: sample-app
description: A Helm chart for deploying applications on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - application
  - kubernetes
  - production
maintainers:
  - name: DevOps Team
    email: devops@example.com
sources:
  - https://github.com/example/sample-app
